### ISSUE TITLE
Deprecated zendframework/zend-http

### ISSUE THREAD

**Issue by BernardRobbins** [shipperhq/library-graphql#2]
Are we able to get zend-http to use laminas/laminas-http instead?

**Comment by zeeshan2523806** [comment]
@wsajason @TravisBernard @wsagen @wsajosh not sure who is the owner, but can we please merge this PR as this is blocker for the people who are using other modules which require laminas/laminas-http module.

**Comment by wsadasmit** [comment]
Hi @BernardRobbins and @zeeshan2523806, thanks for the suggestion, we'll consider this switch.

My understanding is that zend is still interchangeable with laminas and this adaptor from laminas should be able to facilitate compatability in the meantime: https://github.com/laminas/laminas-dependency-plugin

Please let me know if this plugin does not enable compatibility as a workaround.

**Comment by Silarn** [comment]
I've attempted to include the above plugin in my required packages but still encounter dependency issues. I may try the version in the pull request eventually, but this is not the only module that needs updates in my case.

**Comment by zeeshan2523806** [comment]
@wsadasmit if my memory serves me right then Magento actually replaced all the zend modules with laminas and this is the approach which is widely being followed by all the third party developers/distributors as well which are distributing modules through composer.

The problem in my case is also with the third party modules from Amasty which are using laminas/laminas-http as depedency to their module which does not work together with zend-http even after installing the dependency plugin.

**Comment by BernardRobbins** [comment]
@wsadasmit ZF is deprecated in favor of Laminas. They do have compatibility code, but the composer needs to require that instead. I created the pull request that'll fix that.

**Comment by wsajosh** [comment]
We've released a new version which adds support for Magento 2.4.4 and PHP 8.1 and also removes the dependency on Zend in favour of Laminas. Please go ahead and update
