### ISSUE TITLE
Add support for php 8.1

### ISSUE THREAD

**Issue by calin-ImDigital** [shipperhq/library-graphql#4]
Hi, can you please add support for magento 2.4.4 which supports only PHP 8.1 ? Thanks.

**Comment by ibraheemnabeelfauzi** [comment]
Hello, @cdiacon-img  this is something we're working on currently and we're planning on releasing sometime soon. once the dates are established we'll let you know! Appreciate the patience.

**Comment by calin-ImDigital** [comment]
thanks @ibraheemnabeelfauzi because this is a blocker for other shipperhq modules that depends on library-graphql

**Comment by ibraheemnabeelfauzi** [comment]
@cdiacon-img yup! we're aware, we're at it trust me, and we'll roll it out soon. :)

**Comment by wsajosh** [comment]
Hi @cdiacon-img We've released a new version which adds support for Magento 2.4.4 and PHP 8.1. Please go ahead and update
