### ISSUE TITLE
PHP 8.2 Support

### ISSUE THREAD

**Issue by erastl** [shipperhq/library-graphql#6]
We are attempting to upgrade the PHP version on our Magento 2 website to version 8.2, and got an error on the shipperhq library-graphql module. Does this module support PHP 8.2, and if not, do you have an estimate on when that would be available?

**Comment by WSAlewis** [comment]
Hello @erastl, thanks for reaching out to us.

Would you be able to expand further on the error you're seeing?

I'll be relaying this information to our development team for further review.

Lewis Kennedy - ShipperHQ / WebShopApps Support

**Comment by erastl** [comment]
Here is a screenshot from our developers:

![image](https://github.com/shipperhq/library-graphql/assets/49311003/0fc53d09-5794-4f42-80b0-4a52c508b5dd)

**Comment by WSAlewis** [comment]
Hello @erastl, I've gone ahead and passed this along to our development team.

I'll reach out with an update as soon as I have more information share.

Let us know if you have any questions or the status of the issue changes.

**Comment by mamsincl** [comment]
+1 please

**Comment by wsajosh** [comment]
Thanks for raising this, it's been addressed in 20.4.5 which has just been released.
